
print("Successfully imported mwar3_engine.py")

import time
import os

def clear_screen():
	if os.name == 'nt':
		_ = os.system('cls')
   # for mac and linux(here, os.name is 'posix')
	else:
		_ = os.system('clear')

def display_intro():
	print("Welcome to Project Map War!")
	time.sleep(1)
	clear_screen()

def game_version():
	print("THE GAME VERSION IS " + gameversion)
	time.sleep(2)
	main_menu()

def main_menu():
	print("Start Game(1)")
	print("Tutorial(2)")
	print("Exit Game(3)")

	option = ""
	while option != "1" and option != "2" and option != "3": # Makes sure that people don't just imput random crap
		option = input("> ")
	
	if option == "1":
		start_game()
	elif option == "2":
		tutorial()

	return option

def tutorial():
	print("Note: If you see this '> ' with no words explaining it,")
	print("it just means enter in something to continue.")
	time.sleep(2)
	clear_screen()
	map()
	input("> ")
	print("There are alignments for the different countries")
	input("> ")
	clear_screen()
	print("The alignments are Peaceful, Aggressive, and Neutral")
	input("> ")
	clear_screen()
	print("Peaceful countries can only declare war on Aggressive countries that have caused chaos, Aggressive countries can declare")
	print("war on anyone at anytime, and Neutral countries can't delcare war at all but they can fight back.")
	input("> ")
	clear_screen()
	print("In this tutorial, you will delcare war on Country R, which is a Neutral country")
	input("> ")
	clear_screen()
	map()
	print("Invade the upper part of Country R(1) or the lower part(2)")
	option = ""
	while option != "1" and option != "2":
		option = input("> ")

	if option == "1": # Upper part
		clear_screen()
		print("Map of the Current World:")
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  AAAAAAAAAKKKKK")
		print("   AAALLLLLLLLL")
		print("    AAAAABBBBB")
		print("")
		print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSRQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSRRRRRRRQQQQQPPPPPPPPPPPPPPPPP")
		input("> ")
		clear_screen()
		print("Map of the Current World:")
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  AAAAAAAAAKKKKK")
		print("   AAALLLLLLLLL")
		print("    AAAAABBBBB")
		print("")
		print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
		input("> ")
		print("You won!")
		input("> ")
		clear_screen()
		main_menu()

	else:
		clear_screen()
		print("Map of the Current World:")
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  AAAAAAAAAKKKKK")
		print("   AAALLLLLLLLL")
		print("    AAAAABBBBB")
		print("")
		print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSRQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
		input("> ")
		clear_screen()
		print("Map of the Current World:")
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  AAAAAAAAAKKKKK")
		print("   AAALLLLLLLLL")
		print("    AAAAABBBBB")
		print("")
		print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
		input("> ")
		print("You won!")
		input("> ")
		clear_screen()
		main_menu()

def pause():
	print("")
	print("Enter something to continue")
	input("> ")# Doesn't work but I'm keeping it just in case

def map():
	print("Map of the Current World:")
	print("")
	print("")
	print("JJJJIIIIHHHGGGGGGF")
	print(" DDDDDMMMMMMMEEEE")
	print("  AAAAAAAAAKKKKK")
	print("   AAALLLLLLLLL")
	print("    AAAAABBBBB")
	print("")
	print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
	print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
	print("  CCCCCCCSSSSSSSSSSRRRRRQQQQPPPPPPPPPPPPPPPPP")
	print("CCCCCCCCCSSSSSSSRRRRRRRQQQQQPPPPPPPPPPPPPPPPP")

def start_game():
	clear_screen()
	map()
	input("> ")
	print("Country C has declared war on Country Z!")
	print("")
	print("World you like to intervene? Yes(1) or no(2)")

	option = ""
	while option != "1" and option != "2":
		option = input("> ")

	if option == "1": # Yes
		clear_screen()
		map()
		input("> ")
		clear_screen()
		print("Map of the Current World:")
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  AAAAAAAAAKKKKK")
		print("   AAALLLLLLLLL")
		print("    AAAAABBBBB")
		print("")
		print("   ACCACCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
		input("> ")
		print("Meet up(1) or invade elsewhere(2)")
		option = ""
		while option != "1" and option != "2":
			option = input("> ")

		if option == "1": # Meet up
			clear_screen()
			print("Map of the Current World:")
			print("")
			print("")
			print("JJJJIIIIHHHGGGGGGF")
			print(" DDDDDMMMMMMMEEEE")
			print("  AAAAAAAAAKKKKK")
			print("   AAALLLLLLLLL")
			print("    AAAAABBBBB")
			print("")
			print("   AAAACCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
			print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
			print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
			input("> ")
			print("Invade down south(1) or invade right(2)")
			option = ""
			while option != "1" and option != "2":
				option = input("> ")

			if option == "1": # Invade down south
				clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLLLLL")
				print("    AAAAABBBBB")
				print("")
				print("   AACCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    AAACCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLLLLL")
				print("    AAAAABBBBB")
				print("")
				print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				print("You lost!")
				input("> ")
				clear_screen()
				main_menu()

			else: # Invade right
				clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLLLLL")
				print("    AAAAABBBBB")
				print("")
				print("   CCCCACZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLLLLL")
				print("    AAAAABBBBB")
				print("")
				print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				print("You lost!")
				input("")
				clear_screen()
				main_menu()

		else: # Invade elsewhere
			clear_screen()
			print("Map of the Current World:")
			print("")
			print("")
			print("JJJJIIIIHHHGGGGGGF")
			print(" DDDDDMMMMMMMEEEE")
			print("  AAAAAAAAAKKKKK")
			print("   AAALLLLLLLLL")
			print("    AAAAABBBBB")
			print("")
			print("   ACCACCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
			print("    ACAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
			print("  AAACCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
			input("> ")
			print("Meet together(1) or continue to split up(2)")
			option = ""
			while option != "1" and option != "2":
				option = input("> ")

			if option == "1": # Meet together
				clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLLLLL")
				print("    AAAAABBBBB")
				print("")
				print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    AAAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  AAAAACCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				print("Finish off the right side(1) or go down south(2)")
				option = ""
				while option != "1" and option != "2":
					option = input("> ")

				if option == "1": # Finish off the right side
					clear_screen()
					print("Map of the Current World:")
					print("")
					print("")
					print("JJJJIIIIHHHGGGGGGF")
					print(" DDDDDMMMMMMMEEEE")
					print("  AAAAAAAAAKKKKK")
					print("   AAALLLLLLLLL")
					print("    AAAAABBBBB")
					print("")
					print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
					print("    AAAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
					print("  AAAAAAASSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
					print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
					input("> ")
					clear_screen()
					print("Map of the Current World:")
					print("")
					print("")
					print("JJJJIIIIHHHGGGGGGF")
					print(" DDDDDMMMMMMMEEEE")
					print("  AAAAAAAAAKKKKK")
					print("   AAALLLLLLLLL")
					print("    AAAAABBBBB")
					print("")
					print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
					print("    AAAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
					print("  AAAAAAASSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
					print("AAAAAAAAASSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
					input("> ")
					print("You won!")
					input("> ")
					clear_screen()
					main_menu()

				else: # Go down south
					clear_screen()
					print("Map of the Current World:")
					print("")
					print("")
					print("JJJJIIIIHHHGGGGGGF")
					print(" DDDDDMMMMMMMEEEE")
					print("  AAAAAAAAAKKKKK")
					print("   AAALLLLLLLLL")
					print("    AAAAABBBBB")
					print("")
					print("   AACCCCCCZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
					print("    AAACCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
					print("  AAACCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
					print("AAAAAAACCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
					input("> ")
					clear_screen()
					print("Map of the Current World:")
					print("")
					print("")
					print("JJJJIIIIHHHGGGGGGF")
					print(" DDDDDMMMMMMMEEEE")
					print("  AAAAAAAAAKKKKK")
					print("   AAALLLLLLLLL")
					print("    AAAAABBBBB")
					print("")
					print("   AAAACCCCZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
					print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
					print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
					print("ACCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
					input("> ")
					clear_screen()
					print("Map of the Current World:")
					print("")
					print("")
					print("JJJJIIIIHHHGGGGGGF")
					print(" DDDDDMMMMMMMEEEE")
					print("  AAAAAAAAAKKKKK")
					print("   AAALLLLLLLLL")
					print("    AAAAABBBBB")
					print("")
					print("   CCCCCCCCCYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
					print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
					print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
					print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
					input("> ")
					print("You lost!")
					input("> ")
					clear_screen()
					main_menu()

			else: # Continue to split up
				clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLLLLL")
				print("    AAAAABBBBB")
				print("")
				print("   CCCCCCCCZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    ACAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  AAACCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLLLLL")
				print("    AAAAABBBBB")
				print("")
				print("   CCCCCCCCCYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				print("You lost!")
				input("> ")
				clear_screen()
				main_menu()

	else: # No
		print("Country C has declared war on you!")
		input("> ")
		clear_screen()
		print("Map of the Current World:")
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  AAAAAAAAAKKKKK")
		print("   AAALLLLLLLLL")
		print("    CCCCCBBBBB")
		print("")
		print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
		input("> ")
		clear_screen()
		print("Map of the Current World:")
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  CCCAAAAAAKKKKK")
		print("   CCCLLLLLLLLL")
		print("    CCCCCBBBBB")
		print("")
		print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
		input("> ")
		clear_screen()
		print("Map of the Current World:")
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  CCCCCCCCCKKKKK")
		print("   CCCLLLLLLLLL")
		print("    CCCCCBBBBB")
		print("")
		print("   CCCCCCCCCYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("")
		print("You lost you selfish jerk!")
		input("> ")
		clear_screen()
		main_menu()