
import mwar3_engine as m3e
import time
import os

def pmw_title():
	title = "Project Map War"
	os.system("title "+ title)

pmw_title()

def clear_screen():
	os.system("cls")

gameversion = "0.1.0" # The "Phase" Update
	# 0.2.* is reserved for dynamics
	# 0.1.1(mwar5) is reserved for colonization, and possibly an observe mode
	# where all of the countries' decisions are randomized.
	# eventually i would like to make an option where this happens in game, but
	# this could be part of the dynamic update and not earlier.
	# also in 0.1.1 or later, Country F will be playable but every decision with be
	# random and therefore you don't really get to choose what you do
	# also for either dynamic update or earlier, choosing "unhistorical"
	# decisions will make other countries also choose different decisions,
	# as sort of a part 2 to this update
	# the general idea of 0.1.* is that by the end, every country will be playable,
	# and by the end of 0.2, every game will be somewhat dynamic and every
	# country can be interacted with in some way.
	# also consider re-adding the debug menu as it could be useful and it
	# would be easier to implement than if we used Batch.
	#make countries O, N, and P be in a faction called "The Peacekeeping Front"

def main_menu():
	print("Start Game(1)")
	print("Tutorial(2) WARNING! TUTORIAL IS A BIT BUGGY AND WILL BRING YOU BACK TO A DEPRECATED VERSION OF THE MAIN MENU!")
	print("Exit Game(3)")

	option = ""
	while option != "1" and option != "2" and option != "3": # Makes sure that people don't just imput random crap
		option = input("> ")
	
	if option == "1":
		start_game()
	elif option == "2":
		m3e.tutorial()

	return option

def start_game():
	m3e.clear_screen()
	print("Country Select:")
	print("")
	print("Country A(1)")
	print("Country B(2)")
	print("Country C(3)")

	option = ""
	while option != "1" and option != "2" and option != "3": # Makes sure that people don't just input random crap
		option = input("> ")
	
	if option == "1":
		country_a()
	elif option == "2":
		country_b()
	elif option == "3":
		country_c()

	return option

def country_a():
	m3e.clear_screen()
	m3e.map()
	input("> ")
	print("Country C has declared war on Country Z!")
	print("")
	print("World you like to intervene? Yes(1) or no(2)")

	option = ""
	while option != "1" and option != "2":
		option = input("> ")

	if option == "1": # Yes (Phase 1)
		m3e.clear_screen()
		m3e.map()
		input("> ")
		m3e.clear_screen()
		print("Map of the Current World:")
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  AAAAAAAAAKKKKK")
		print("   AAALLLLBBBBB")
		print("    AAAAABBBBB")
		print("")
		print("   ACCACCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSRQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSRRRRRRRQQQQQPPPPPPPPPPPPPPPPP")
		input("> ")
		print("Meet up(1) or invade elsewhere(2)")
		option = ""
		while option != "1" and option != "2":
			option = input("> ")

		if option == "1": # Meet up (Phase 2)
			m3e.clear_screen()
			print("Map of the Current World:")
			print("")
			print("")
			print("JJJJIIIIHHHGGGGGGF")
			print(" DDDDDMMMMMMMEEEE")
			print("  AAAAAAAAAKKKKK")
			print("   AAALLLLBBBBB")
			print("    AAAAALLBBB")
			print("")
			print("   AAAACCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
			print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
			print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
			input("> ")
			print("Invade down south(1) or invade right(2)")
			option = ""
			while option != "1" and option != "2":
				option = input("> ")

			if option == "1": # Invade down south (Phase 3)
				m3e.clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLBBBB")
				print("    AAAAALLLLL")
				print("")
				print("   AACCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    AAACCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				m3e.clear_screen()
				print("Map of the Current World:") # Phase 4
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLLLLL")
				print("    AAAAALLLLL")
				print("")
				print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				print("You lost!")
				input("> ")
				m3e.clear_screen()
				main_menu()

			else: # Invade right (Phase 3)
				m3e.clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLBBBB")
				print("    AAAAALLLLL")
				print("")
				print("   CCCCACZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				m3e.clear_screen()
				print("Map of the Current World:") # Phase 4
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLLLLL")
				print("    AAAAALLLLL")
				print("")
				print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				print("You lost!")
				input("")
				m3e.clear_screen()
				main_menu()

		else: # Invade elsewhere (Phase 2)
			m3e.clear_screen()
			print("Map of the Current World:")
			print("")
			print("")
			print("JJJJIIIIHHHGGGGGGF")
			print(" DDDDDMMMMMMMEEEE")
			print("  AAAAAAAAAKKKKK")
			print("   AAALLLLBBBBB")
			print("    AAAAALLBBB")
			print("")
			print("   ACCACCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
			print("    ACAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
			print("  AAACCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
			input("> ")
			print("Meet together(1) or continue to split up(2)")
			option = ""
			while option != "1" and option != "2":
				option = input("> ")

			if option == "1": # Meet together (Phase 3)
				m3e.clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLBBBB")
				print("    AAAAALLLLL")
				print("")
				print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    AAAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  AAAAACCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				print("Finish off the right side(1) or go down south(2)")
				option = ""
				while option != "1" and option != "2":
					option = input("> ")

				if option == "1": # Finish off the right side (Phase 4)
					m3e.clear_screen()
					print("Map of the Current World:")
					print("")
					print("")
					print("JJJJIIIIHHHGGGGGGF")
					print(" DDDDDMMMMMMMEEEE")
					print("  AAAAAAAAAKKKKK")
					print("   AAALLLLLLLLL")
					print("    AAAAALLLLL")
					print("")
					print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
					print("    AAAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
					print("  AAAAAAASSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
					print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
					input("> ")
					m3e.clear_screen()
					print("Map of the Current World:") # Phase 5
					print("")
					print("")
					print("JJJJIIIIHHHGGGGGGF")
					print(" DDDDDMMMMMMMEEEE")
					print("  AAAAAAAAAKKKKK")
					print("   AAALLLLLLLLL")
					print("    AAAAALLLLL")
					print("")
					print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
					print("    AAAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
					print("  AAAAAAASSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
					print("AAAAAAAAASSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
					input("> ")
					print("You won!")
					input("> ")
					m3e.clear_screen()
					main_menu()

				else: # Go down south (Phase 4)
					m3e.clear_screen()
					print("Map of the Current World:")
					print("")
					print("")
					print("JJJJIIIIHHHGGGGGGF")
					print(" DDDDDMMMMMMMEEEE")
					print("  AAAAAAAAAKKKKK")
					print("   AAALLLLLLLLL")
					print("    AAAAALLLLL")
					print("")
					print("   AACCCCCCZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
					print("    AAACCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
					print("  AAACCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
					print("AAAAAAACCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
					input("> ")
					m3e.clear_screen()
					print("Map of the Current World:") #Phase 5
					print("")
					print("")
					print("JJJJIIIIHHHGGGGGGF")
					print(" DDDDDMMMMMMMEEEE")
					print("  AAAAAAAAAKKKKK")
					print("   AAALLLLLLLLL")
					print("    AAAAALLLLL")
					print("")
					print("   AAAACCCCZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
					print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
					print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
					print("ACCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
					input("> ")
					m3e.clear_screen()
					print("Map of the Current World:") # Phase 6
					print("")
					print("")
					print("JJJJIIIIHHHGGGGGGF")
					print(" DDDDDMMMMMMMEEEE")
					print("  AAAAAAAAAKKKKK")
					print("   AAALLLLLLLLL")
					print("    AAAAALLLLL")
					print("")
					print("   CCCCCCCCCYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
					print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
					print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
					print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
					input("> ")
					print("You lost!")
					input("> ")
					m3e.clear_screen()
					main_menu()

			else: # Continue to split up (Phase 3)
				m3e.clear_screen()
				print("Map of the Current World:")
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLBBBB")
				print("    AAAAALLLLL")
				print("")
				print("   CCCCCCCCZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    ACAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  AAACCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				m3e.clear_screen()
				print("Map of the Current World:") # Phase 4
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE")
				print("  AAAAAAAAAKKKKK")
				print("   AAALLLLLLLLL")
				print("    AAAAALLLLL")
				print("")
				print("   CCCCCCCCCYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				input("> ")
				print("You lost!")
				input("> ")
				m3e.clear_screen()
				main_menu()

	else: # No (Phase 0)
		clear_screen()
		m3e.map() # Phase 0
		print("Country C has declared war on you!")
		input("> ")
		m3e.clear_screen()
		print("Map of the Current World:") # Phase 1
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  AAAAAAAAAKKKKK")
		print("   AAALLLLBBBBB")
		print("    CCCCCBBBBB")
		print("")
		print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSRQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSRRRRRRRQQQQQPPPPPPPPPPPPPPPPP")
		input("> ")
		m3e.clear_screen()
		print("Map of the Current World:") # Phase 2
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  CCCAAAAAAKKKKK")
		print("   CCCLLLLBBBBB")
		print("    CCCCCLLBBB")
		print("")
		print("   CCCCCCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
		input("> ")
		m3e.clear_screen()
		print("Map of the Current World:") # Phase 3
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  CCCCCCCCCKKKKK")
		print("   CCCLLLLLBBBB")
		print("    CCCCCLLLLL")
		print("")
		print("   CCCCCCCCCYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("")
		print("You lost you selfish jerk!")
		input("> ")
		m3e.clear_screen()
		main_menu()

def country_b():
	m3e.clear_screen()
	m3e.map()
	input("> ")
	clear_screen()
	m3e.map()
	print("")
	print("Right now you can only delcare war on Country A, which is a Peaceful country, or Country Z, which is a Neutral country.")
	input("> ")
	clear_screen()
	m3e.map()
	print("")
	print("Invade Country A(1)")
	print("Invade Country Z(2)")

	option = ""
	while option != "1" and option != "2": # Makes sure that people don't just input random crap
		option = input("> ")

	if option == "1": #Country A (Phase 1)
		clear_screen()
		print("Map of the Current World:")
		print("")
		print("")
		print("JJJJIIIIHHHGGGGGGF")
		print(" DDDDDMMMMMMMEEEE")
		print("  AAAAAAAAAKKKKK")
		print("   AAALLLLLLLLL")
		print("    AABBBBBBBB")
		print("")
		print("   ACCACCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
		print("    CCCCCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
		print("  CCCCCCCSSSSSSSSSSRQQQQQQQQPPPPPPPPPPPPPPPPP")
		print("CCCCCCCCCSSSSSSSRRRRRRRQQQQQPPPPPPPPPPPPPPPPP")
		print("")
		print("Invade left and up(1) or invade left and stay(2)")
		option = ""
		while option != "1" and option != "2": # Makes sure that people don't just input random crap
			option = input("> ")
		
		if option == "1": #Invade left and up (Phase 2)
			clear_screen()
			print("Map of the Current World:")
			print("")
			print("")
			print("JJJJIIIIHHHGGGGGGF")
			print(" DDDDDMMMMMMMEEEE")
			print("  AAAAAAAAAKKKKK")
			print("   BBBLLLLLLLLL")
			print("    BBBBBBBBBB")
			print("")
			print("   ACCACCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
			print("    ACAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
			print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("")
			input("> ")
			clear_screen()
			print("Map of the Current World:") #Phase 3
			print("")
			print("")
			print("JJJJIIIIHHHGGGGGGF")
			print(" DDDDDMMMMMMMEEEE")
			print("  AAAAAAAAAKKKKK")
			print("   AAALLLLLLLLL")
			print("    AAABBBBBBB")
			print("")
			print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
			print("    ZZZZZTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
			print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("")
			input("> ")
			clear_screen()
			print("Map of the Current World:") #Phase 4
			print("")
			print("")
			print("JJJJIIIIHHHGGGGGGF")
			print(" DDDDDMMMMMMMEEEE")
			print("  AAAAAAAAAKKKKK")
			print("   AAALLLLLLLLL")
			print("    AAAAAAAAAA")
			print("")
			print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
			print("    ZZZZZTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
			print("  CCZZZZZSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("")
			input("> ")
			print("You lose!")
			input("> ")
			clear_screen()
			main_menu()

		elif option == "2": #Invade left and stay (Phase 2)
			clear_screen()
			print("Map of the Current World:")
			print("")
			print("")
			print("JJJJIIIIHHHGGGGGGF")
			print(" DDDDDMMMMMMMEEEE")
			print("  AAAAAAAAAKKKKK")
			print("   AAALLLLLLLLL")
			print("    BBBBBBBBBB")
			print("")
			print("   ACCACCZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
			print("    ACAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
			print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("")
			input("> ")
			clear_screen()
			print("Map of the Current World:") #Phase 3
			print("")
			print("")
			print("JJJJIIIIHHHGGGGGGF")
			print(" DDDDDMMMMMMMEEEE")
			print("  AAAAAAAAAKKKKK")
			print("   AAALLLLLLLLL")
			print("    AABBBBBBBB")
			print("")
			print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
			print("    AAAAATTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
			print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
			print("")
			input("> ")
			print("Invade Back(1) or surrender(2)")

			option = ""
			while option != "1" and option != "2":
				option = input("> ")

			if option == "1":
				clear_screen()
				print("Map of the Current World:") #Invade back(Phase 4)
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE ")
				print("  AAAAAAAAAKKKKK  ")
				print("   BBBLLLLLLLLL	 ")
				print("    BBBBBBBBBB	 ")
				print("")
				print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    CCACCTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCCCCCCSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("")
				print("Stay(1) or keep pushing.")

			elif option == "2":
				clear_screen()
				print("Map of the Current World:") #Surrender(Phase 4)
				print("")
				print("")
				print("JJJJIIIIHHHGGGGGGF")
				print(" DDDDDMMMMMMMEEEE ")
				print("  AAAAAAAAAKKKKK  ")
				print("   AAALLLLLLLLL   ")
				print("    AAAAAAAAAA    ")
				print("")
				print("   AAAAZZZZZYYYXWWVVVVVVVVVVOOOOOOOOONNNNNNNN")
				print("    ZZZZZTTTTTTTTTUUUUUUUUUUOOOOOOOOOOOOOOOOO")
				print("  CCZZZZZSSSSSSSSSSQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("CCCCCCCCCSSSSSSSQQQQQQQQQQQQPPPPPPPPPPPPPPPPP")
				print("")
				print("You lose!")
				input("> ")
				country_b()

		return option

	elif option == "2": #Country L (Phase 1)
		print("sike2")
		input("d")
		country_b()

	return option

def country_c():
	norp = "norp"
	print(norp)
	time.sleep(1.5)
	clear_screen()
	main_menu()

time.sleep(0.5)
m3e.clear_screen()
m3e.display_intro()
main_menu()
